-- ============================================================================
--  BidTagglia: company directory.
--  Run in Supabase -> SQL Editor. Safe to re-run.
--
--  The Companies tab lists every company we've priced (the Company field on
--  pricing_quotes) plus anything added here. This table holds the details we
--  keep about each one. `name` is the key and matches the quote spelling.
-- ============================================================================

create table if not exists public.companies (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  type       text,
  industry   text,
  phone      text,
  website    text,
  notes      text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.companies enable row level security;
drop policy if exists "anon full access companies" on public.companies;
create policy "anon full access companies" on public.companies
  for all to anon using (true) with check (true);
