-- ============================================================================
--  BidTagglia — complete database setup.
--
--  Paste this whole file into the Supabase SQL Editor of a FRESH project and
--  press Run. It creates every table the app uses, plus the indexes and
--  access policies.
--
--  The app starts EMPTY — no bids, no quotes. The only row created is the
--  admin on the invite list, because an empty invite list would lock
--  everyone out, including the person who needs to add everyone else.
--
--  Safe to re-run.
--
--  Replaces the older piecemeal files (supabase_migration / _pricing_team /
--  _companies / _members / _crm), which had drifted apart from each other.
-- ============================================================================


-- ---------------------------------------------------------------------------
--  Opportunities — the bids themselves. One column per form field; the app
--  maps these to camelCase keys via COLUMN_MAP in dashboard.js.
--
--  id is a uuid, and the child tables below store it as text, so the two
--  always compare equal however the id is generated.
-- ---------------------------------------------------------------------------

create table if not exists public.opportunities (
  id                      uuid primary key default gen_random_uuid(),
  created_at              timestamptz not null default now(),

  name                    text,
  bid_due_date            date,
  bid_due_time            time,
  division                text,
  internal_bid_number     text,
  project_manager         text,
  status                  text,
  lead_estimator          text,

  owner_customer          text,
  cm                      text[] default '{}',
  gc                      text[] default '{}',
  architect               text,
  engineer                text,
  local_unions            text[] default '{}',

  market_segment          text,
  industry                text,
  bid_type                text,
  delivery_method         text,

  flags                   text[] default '{}',
  description             text,

  project_address         text,
  city                    text,
  zip_code                text,
  state                   text,

  budgeted_project_value  numeric,
  budgeted_cost           numeric,
  final_price             numeric,
  budgeted_labor_hours    numeric,
  budgeted_square_footage numeric,
  est_start_date          date,
  est_end_date            date,
  docs_received_date      date
);

create index if not exists opportunities_status_idx on public.opportunities(status);
create index if not exists opportunities_due_idx    on public.opportunities(bid_due_date);


-- ---------------------------------------------------------------------------
--  Pricing quotes + project team — both hang off an opportunity.
-- ---------------------------------------------------------------------------

create table if not exists public.pricing_quotes (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  type           text not null check (type in ('proposal','budgetary')),
  company        text,
  price          numeric,
  price_sent_on  date,
  notes          text,
  status         text not null default 'Draft'
                   check (status in ('Draft','Sent','Lost','Withdrawn')),
  created_at     timestamptz default now()
);
create index if not exists pricing_quotes_opp_idx
  on public.pricing_quotes(opportunity_id);

create table if not exists public.project_members (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  name           text not null,
  role           text,
  created_at     timestamptz default now()
);
create index if not exists project_members_opp_idx
  on public.project_members(opportunity_id);


-- ---------------------------------------------------------------------------
--  Companies — the Companies tab. NOTE: this table was missing from the old
--  project, so that tab has been failing silently. It exists here.
-- ---------------------------------------------------------------------------

create table if not exists public.companies (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  type       text,
  industry   text,
  phone      text,
  website    text,
  notes      text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- ---------------------------------------------------------------------------
--  Contacts + activities.
-- ---------------------------------------------------------------------------

create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text,
  phone      text,
  company    text,
  notes      text,
  created_at timestamptz not null default now()
);
create index if not exists contacts_company_idx on public.contacts(company);

create table if not exists public.activities (
  id             bigint generated by default as identity primary key,
  title          text not null,
  type           text,
  scheduled_date date,
  opportunity_id text,
  contact_id     bigint references public.contacts(id) on delete set null,
  notes          text,
  created_at     timestamptz not null default now()
);
create index if not exists activities_scheduled_idx
  on public.activities(scheduled_date);
create index if not exists activities_opportunity_idx
  on public.activities(opportunity_id);


-- ---------------------------------------------------------------------------
--  App members — the invite list. Only addresses here can sign in; access.js
--  enforces it. first_seen_at / last_active_at stay null until someone takes
--  up their invite, which is what shows them as "Invited".
-- ---------------------------------------------------------------------------

create table if not exists public.app_members (
  id             bigint generated by default as identity primary key,
  identity       text not null unique,
  name           text,
  email          text,
  source         text not null default 'microsoft'
                   check (source in ('microsoft', 'manual')),
  role           text not null default 'User'
                   check (role in ('Admin', 'Admin Super User', 'Super User',
                                   'User', 'Test')),
  blocked        boolean not null default false,
  invited_at     timestamptz not null default now(),
  invited_by     text,
  first_seen_at  timestamptz,
  last_active_at timestamptz
);
create index if not exists app_members_identity_idx
  on public.app_members(identity);


-- ---------------------------------------------------------------------------
--  Access policies.
--
--  WARNING — these grant the public key full read AND write on every table,
--  which is what the app relies on today. It also means anyone holding the key
--  can add themselves to app_members and sign in. Tightening this is tracked
--  separately; it is deliberately carried over unchanged so nothing breaks
--  during the move.
-- ---------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array['opportunities','pricing_quotes','project_members',
                           'companies','contacts','activities','app_members']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "anon full access" on public.%I', t);
    execute format('create policy "anon full access" on public.%I
                      for all to anon using (true) with check (true)', t);
  end loop;
end $$;


-- ---------------------------------------------------------------------------
--  Seed the admin.
--
--  access.js turns away anyone who isn't on this list, and only ADMIN_EMAIL
--  sees the Users tab that adds people to it — so without this row nobody can
--  get in at all. Everyone else gets invited from inside the app.
-- ---------------------------------------------------------------------------

insert into public.app_members (identity, name, email, role, invited_at)
values ('trossi@battag.com', 'Tre Rossi', 'trossi@battag.com', 'Admin', now())
on conflict (identity) do update
  set role = 'Admin', blocked = false;


-- Sanity check — expect 1 member, 0 bids.
select
  (select count(*) from public.app_members)   as members,
  (select count(*) from public.opportunities) as opportunities;
