-- ============================================================================
--  BidTagglia: child tables for an opportunity's pricing quotes and team.
--  Run in Supabase -> SQL Editor. Safe to re-run.
--
--  opportunity_id is stored as TEXT (the opportunities row id, stringified) so
--  it works whether opportunities.id is uuid or bigint. The app deletes child
--  rows when an opportunity is removed.
-- ============================================================================

-- Pricing quotes (proposal / budgetary) ---------------------------------------
create table if not exists public.pricing_quotes (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  type           text not null check (type in ('proposal','budgetary')),
  company        text,
  price          numeric,
  price_sent_on  date,
  notes          text,
  status         text not null default 'Draft'
                   check (status in ('Draft','Sent','Lost','Withdrawn')),
  created_at     timestamptz default now()
);
create index if not exists pricing_quotes_opp_idx
  on public.pricing_quotes(opportunity_id);

alter table public.pricing_quotes enable row level security;
drop policy if exists "anon full access pricing" on public.pricing_quotes;
create policy "anon full access pricing" on public.pricing_quotes
  for all to anon using (true) with check (true);

-- Project team members --------------------------------------------------------
create table if not exists public.project_members (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  name           text not null,
  role           text,
  created_at     timestamptz default now()
);
create index if not exists project_members_opp_idx
  on public.project_members(opportunity_id);

alter table public.project_members enable row level security;
drop policy if exists "anon full access members" on public.project_members;
create policy "anon full access members" on public.project_members
  for all to anon using (true) with check (true);
