-- ============================================================================
--  BidTagglia — complete database setup.
--
--  Paste this whole file into the Supabase SQL Editor of a FRESH project and
--  press Run. It creates every table the app uses, the indexes and access
--  policies, and carries over the rows from the old project.
--
--  Safe to re-run: the tables are created only if missing. The inserts at the
--  bottom are NOT — running the file twice would duplicate those rows, so
--  delete that section once it has run successfully.
--
--  Replaces the older piecemeal files (supabase_migration / _pricing_team /
--  _companies / _members / _crm), which had drifted apart from each other.
-- ============================================================================


-- ---------------------------------------------------------------------------
--  Opportunities — the bids themselves. One column per form field; the app
--  maps these to camelCase keys via COLUMN_MAP in dashboard.js.
--
--  id is a uuid, and the child tables below store it as text, so the two
--  always compare equal however the id is generated.
-- ---------------------------------------------------------------------------

create table if not exists public.opportunities (
  id                      uuid primary key default gen_random_uuid(),
  created_at              timestamptz not null default now(),

  name                    text,
  bid_due_date            date,
  bid_due_time            time,
  division                text,
  internal_bid_number     text,
  project_manager         text,
  status                  text,
  lead_estimator          text,

  owner_customer          text,
  cm                      text[] default '{}',
  gc                      text[] default '{}',
  architect               text,
  engineer                text,
  local_unions            text[] default '{}',

  market_segment          text,
  industry                text,
  bid_type                text,
  delivery_method         text,

  flags                   text[] default '{}',
  description             text,

  project_address         text,
  city                    text,
  zip_code                text,
  state                   text,

  budgeted_project_value  numeric,
  budgeted_cost           numeric,
  final_price             numeric,
  budgeted_labor_hours    numeric,
  budgeted_square_footage numeric,
  est_start_date          date,
  est_end_date            date,
  docs_received_date      date
);

create index if not exists opportunities_status_idx on public.opportunities(status);
create index if not exists opportunities_due_idx    on public.opportunities(bid_due_date);


-- ---------------------------------------------------------------------------
--  Pricing quotes + project team — both hang off an opportunity.
-- ---------------------------------------------------------------------------

create table if not exists public.pricing_quotes (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  type           text not null check (type in ('proposal','budgetary')),
  company        text,
  price          numeric,
  price_sent_on  date,
  notes          text,
  status         text not null default 'Draft'
                   check (status in ('Draft','Sent','Lost','Withdrawn')),
  created_at     timestamptz default now()
);
create index if not exists pricing_quotes_opp_idx
  on public.pricing_quotes(opportunity_id);

create table if not exists public.project_members (
  id             bigint generated by default as identity primary key,
  opportunity_id text not null,
  name           text not null,
  role           text,
  created_at     timestamptz default now()
);
create index if not exists project_members_opp_idx
  on public.project_members(opportunity_id);


-- ---------------------------------------------------------------------------
--  Companies — the Companies tab. NOTE: this table was missing from the old
--  project, so that tab has been failing silently. It exists here.
-- ---------------------------------------------------------------------------

create table if not exists public.companies (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  type       text,
  industry   text,
  phone      text,
  website    text,
  notes      text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- ---------------------------------------------------------------------------
--  Contacts + activities.
-- ---------------------------------------------------------------------------

create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text,
  phone      text,
  company    text,
  notes      text,
  created_at timestamptz not null default now()
);
create index if not exists contacts_company_idx on public.contacts(company);

create table if not exists public.activities (
  id             bigint generated by default as identity primary key,
  title          text not null,
  type           text,
  scheduled_date date,
  opportunity_id text,
  contact_id     bigint references public.contacts(id) on delete set null,
  notes          text,
  created_at     timestamptz not null default now()
);
create index if not exists activities_scheduled_idx
  on public.activities(scheduled_date);
create index if not exists activities_opportunity_idx
  on public.activities(opportunity_id);


-- ---------------------------------------------------------------------------
--  App members — the invite list. Only addresses here can sign in; access.js
--  enforces it. first_seen_at / last_active_at stay null until someone takes
--  up their invite, which is what shows them as "Invited".
-- ---------------------------------------------------------------------------

create table if not exists public.app_members (
  id             bigint generated by default as identity primary key,
  identity       text not null unique,
  name           text,
  email          text,
  source         text not null default 'microsoft'
                   check (source in ('microsoft', 'manual')),
  role           text not null default 'User'
                   check (role in ('Admin', 'Admin Super User', 'Super User',
                                   'User', 'Test')),
  blocked        boolean not null default false,
  invited_at     timestamptz not null default now(),
  invited_by     text,
  first_seen_at  timestamptz,
  last_active_at timestamptz
);
create index if not exists app_members_identity_idx
  on public.app_members(identity);


-- ---------------------------------------------------------------------------
--  Access policies.
--
--  WARNING — these grant the public key full read AND write on every table,
--  which is what the app relies on today. It also means anyone holding the key
--  can add themselves to app_members and sign in. Tightening this is tracked
--  separately; it is deliberately carried over unchanged so nothing breaks
--  during the move.
-- ---------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array['opportunities','pricing_quotes','project_members',
                           'companies','contacts','activities','app_members']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "anon full access" on public.%I', t);
    execute format('create policy "anon full access" on public.%I
                      for all to anon using (true) with check (true)', t);
  end loop;
end $$;


-- ============================================================================
--  Data carried over from the old project (delete this section after one run)
-- ============================================================================

-- opportunities: 16 row(s)
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('a3011f17-2dbb-40b1-9053-d6f2d2001e90', '2026-08-03T12:43:55.463445+00:00', 'CHOP Brandywine Shell Fit Out', '2026-02-27', 'BEI', '', '', 'Lost', 'Robby Bolen', 'CHOP', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 430660, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('29b4e0b6-95f9-40aa-85cb-12da35c4fb28', '2026-08-03T12:42:39.747276+00:00', 'Bayhealth Interim Helipad', '2026-05-07', 'BEI', '', '', 'Won', 'Robby Bolen', 'Bayhealth', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 27580, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('2c7c3be0-bd60-46db-8e49-a1f36c152ee1', '2026-08-03T12:27:02.215997+00:00', 'ACE Glassboro', '2026-08-31', 'BPS', '26-050', '', 'Pending', 'Cameron Williams', 'ACE', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 355500, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('5e227d24-740f-4620-8cb6-e8c8169b952d', '2026-08-03T12:25:19.127659+00:00', 'PEPCO LTIIP Sub Retirement', '2026-08-14', 'BPS', '26-059', '', 'Pending', 'Cameron Williams', 'PECO', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 5000000, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('0d75f862-e0c7-4b5e-b52e-e6d34278f694', '2026-08-03T12:33:27.528748+00:00', 'Central Hudson KM Line', '2023-12-05', 'BEI', '23-711', '', 'Lost', 'Cameron Williams', 'Central Hudson Gas and Electric', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 4000000, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('fca3d302-767f-4041-ba48-401e464380a8', '2026-08-03T12:35:01.934546+00:00', 'Citizens Bank Bala Cynwyd', '2026-06-30', 'BIT', '26-088', '', 'Pending', 'Roy Dowell', 'Citizens Bank', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 61732, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('841a86c6-ca4b-4a81-8f2b-bfad3c2540b8', '2026-08-03T12:36:01.668465+00:00', 'Citizens Bank Newark NJ ITM', '2026-06-12', 'BIT', '26-086', '', 'Pending', 'Roy Dowell', 'Citizens Bank', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 10470, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('3c13cab2-053c-4209-be52-02dc4be1c55a', '2026-08-03T12:41:01.893028+00:00', 'CCHS MOB 2nd Floor', '2026-08-04', 'BEI', '', '', 'Bidding', 'Robby Bolen', 'CCHS(Christiana Care)', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 150000, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('a322f466-a957-46e1-8f43-f2330931c607', '2026-08-03T12:39:38.184342+00:00', 'Starbucks Sharon Hill', '2026-03-09', 'BIT', '', '', 'Lost', 'Roy Dowell', 'Starbucks', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 14900, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('eae8c278-19be-403c-a309-97aea497715f', '2026-08-03T12:37:37.99107+00:00', 'LPL Financial Bedminster NJ', '2025-12-01', 'BIT', '', '', 'Won', 'Roy Dowell', 'LPL Financial', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 5745, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('419992ae-8ebb-474e-a3dc-5364e37dc157', '2026-08-03T12:32:20.954624+00:00', 'Stockley Center', '2025-04-01', 'BPS', '24-018', '', 'Lost', 'Cameron Williams', 'State of Delaware', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 10000000, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('6df0fb65-3146-4396-8a59-0edb30fe34dc', '2026-08-03T12:31:17.102965+00:00', 'Sligo/Vaness indoor FEP', '2023-05-17', 'BEI', '23-307', '', 'Won', 'Cameron Williams', 'PEPCO', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 566300, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('51754715-94f2-4ce8-ae87-76a75745f41c', '2026-08-03T12:29:05.225736+00:00', 'USCG B-3 Enterprises', '2024-03-11', 'BPS', '24-013', '', 'Won', 'Cameron Williams', 'U.S. Coast Guard', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 150000, null, null, null, null, null, null, null, null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('6ced6168-f3af-4f7b-b207-d538929a8f93', '2026-08-03T15:32:37.794361+00:00', 'Big Job', '2026-08-07', 'BIT', '26-123456', '', 'Bidding', 'Bill Ossowski', 'LPL Financial', '{}', '', '', '{"313-T"}', 'Commercial', 'Banking', 'Hard Bid/Lump Sum', 'Design Build', '{"Certified Payroll"}', '', '1100 Pennsylvania Ave', 'Washington DC', '', '', 10000000, null, null, null, null, null, null, '17:00:00', null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('e219c356-6a74-45c8-ad47-f3039c581f26', '2026-08-03T13:14:04.030803+00:00', 'Test', '2026-09-10', 'BEI', '27-000', '', 'Bidding', 'Tre Rossi', 'Test Company', '{}', '', '', '{}', '', 'Government', '', '', '{}', '', '', '', '', '', 5000, null, null, null, null, null, null, '02:00:00', null, '{}');
insert into public.opportunities (id, created_at, name, bid_due_date, division, internal_bid_number, project_manager, status, lead_estimator, owner_customer, cm, architect, engineer, local_unions, market_segment, industry, bid_type, delivery_method, flags, description, project_address, city, zip_code, state, budgeted_project_value, budgeted_cost, budgeted_labor_hours, budgeted_square_footage, est_start_date, est_end_date, docs_received_date, bid_due_time, final_price, gc) values ('42214616-87fc-46c9-ac41-88ecd8137a21', '2026-08-03T12:45:33.642968+00:00', 'Walmart Georgetown', '2026-05-22', 'BEI', '', '', 'Won', 'Robby Bolen', 'Walmart', '{}', '', '', '{}', '', '', '', '', '{}', '', '', '', '', '', 5000, null, null, null, null, null, null, null, null, '{}');

-- pricing_quotes: 20 row(s)
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('42214616-87fc-46c9-ac41-88ecd8137a21', 'proposal', 'UHC Construction', 5000, '2026-07-16', null, 'Draft', '2026-08-03T12:52:26.203717+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('a3011f17-2dbb-40b1-9053-d6f2d2001e90', 'proposal', 'WEBCO Construction', 430660, null, null, 'Draft', '2026-08-03T12:53:38.381196+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('a3011f17-2dbb-40b1-9053-d6f2d2001e90', 'proposal', 'Perryman Construction', null, null, null, 'Draft', '2026-08-03T12:53:54.303013+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('29b4e0b6-95f9-40aa-85cb-12da35c4fb28', 'proposal', 'Whiting Turner', 27580, null, null, 'Draft', '2026-08-03T12:54:52.969367+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('3c13cab2-053c-4209-be52-02dc4be1c55a', 'proposal', 'CSG(Construction Services Group)', null, null, null, 'Draft', '2026-08-03T12:55:59.749825+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('3c13cab2-053c-4209-be52-02dc4be1c55a', 'proposal', 'Whiting Turner', null, null, null, 'Draft', '2026-08-03T12:56:06.234863+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('3c13cab2-053c-4209-be52-02dc4be1c55a', 'proposal', 'HSC', null, null, null, 'Draft', '2026-08-03T12:56:09.453616+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('a322f466-a957-46e1-8f43-f2330931c607', 'proposal', 'Rycon', 14900, null, null, 'Draft', '2026-08-03T12:56:50.8906+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('eae8c278-19be-403c-a309-97aea497715f', 'proposal', 'Turner & Townsend', 5745, null, null, 'Draft', '2026-08-03T12:58:20.507079+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('841a86c6-ca4b-4a81-8f2b-bfad3c2540b8', 'proposal', 'CItizens Bank', 10470, null, null, 'Draft', '2026-08-03T12:58:52.774937+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('fca3d302-767f-4041-ba48-401e464380a8', 'proposal', 'Citizens Bank', 61732, null, null, 'Draft', '2026-08-03T12:59:22.114826+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('0d75f862-e0c7-4b5e-b52e-e6d34278f694', 'proposal', 'Central Hudson Gas and Electric', null, null, null, 'Draft', '2026-08-03T13:00:01.148776+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('419992ae-8ebb-474e-a3dc-5364e37dc157', 'proposal', 'Fayda Engineering & Energy Solutions', null, null, null, 'Draft', '2026-08-03T13:00:46.52822+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('6df0fb65-3146-4396-8a59-0edb30fe34dc', 'proposal', 'BAI', null, null, null, 'Draft', '2026-08-03T13:01:25.700342+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('51754715-94f2-4ce8-ae87-76a75745f41c', 'proposal', 'B-3 Enterprises', null, null, null, 'Draft', '2026-08-03T13:02:11.067594+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('5e227d24-740f-4620-8cb6-e8c8169b952d', 'proposal', 'PECO', null, null, null, 'Draft', '2026-08-03T13:03:07.401832+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('e219c356-6a74-45c8-ad47-f3039c581f26', 'proposal', 'Test Company 2', 10000, null, null, 'Draft', '2026-08-03T13:14:24.103746+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('6ced6168-f3af-4f7b-b207-d538929a8f93', 'proposal', 'BAI', 10150000, '2026-08-04', null, 'Draft', '2026-08-04T15:39:05.663828+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('6ced6168-f3af-4f7b-b207-d538929a8f93', 'proposal', 'Turner & Townsend', 1050000, '2026-08-05', null, 'Sent', '2026-08-04T14:56:01.945927+00:00');
insert into public.pricing_quotes (opportunity_id, type, company, price, price_sent_on, notes, status, created_at) values ('6ced6168-f3af-4f7b-b207-d538929a8f93', 'proposal', 'test new', 2, null, null, 'Draft', '2026-08-26T18:47:01.069854+00:00');

-- project_members: no rows to carry over

-- contacts: no rows to carry over

-- activities: no rows to carry over

-- app_members: 3 row(s)
insert into public.app_members (identity, name, email, source, role, blocked, first_seen_at, last_active_at, invited_at, invited_by) values ('rcarruthers@battag.com', 'Ryan Carruthers', 'rcarruthers@battag.com', 'microsoft', 'Admin', false, '2026-08-26T18:47:36.308+00:00', '2026-08-26T18:47:36.308+00:00', '2026-08-26T18:45:52.52331+00:00', 'trossi@battag.com');
insert into public.app_members (identity, name, email, source, role, blocked, first_seen_at, last_active_at, invited_at, invited_by) values ('rdowell@battag.com', 'Roy Dowell', 'rdowell@battag.com', 'microsoft', 'Admin', false, null, null, '2026-08-26T18:48:01.681602+00:00', 'trossi@battag.com');
insert into public.app_members (identity, name, email, source, role, blocked, first_seen_at, last_active_at, invited_at, invited_by) values ('trossi@battag.com', 'Tre Rossi', 'trossi@battag.com', 'microsoft', 'Admin', false, '2026-08-26T18:33:36.172+00:00', '2026-08-27T11:49:56.841+00:00', '2026-08-26T18:33:25.265626+00:00', null);

-- Sanity check — expect 16 bids, 20 quotes, 3 members.
select
  (select count(*) from public.opportunities)  as opportunities,
  (select count(*) from public.pricing_quotes) as quotes,
  (select count(*) from public.app_members)    as members;
