-- ============================================================================
--  BidTagglia: app members / user directory.
--  Run in Supabase -> SQL Editor. Safe to re-run.
--
--  Every person who signs in (Microsoft SSO or the manual fallback) gets a row
--  the first time they land on the dashboard. `identity` is the key: the org
--  email for SSO users, the username for manual ones.
--
--  `role` is recorded but NOT yet enforced anywhere in the app — the only
--  permission that does anything today is the hard-coded admin email in
--  users.js (trossi@battag.com), which is what reveals the Users tab.
-- ============================================================================

create table if not exists public.app_members (
  id             bigint generated by default as identity primary key,
  identity       text not null unique,          -- email (SSO) or username (manual)
  name           text,
  email          text,
  source         text not null default 'microsoft'
                   check (source in ('microsoft', 'manual')),
  role           text not null default 'User'
                   check (role in ('Admin', 'Admin Super User', 'Super User',
                                   'User', 'Test')),
  blocked        boolean not null default false,
  first_seen_at  timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);

create index if not exists app_members_identity_idx
  on public.app_members(identity);

alter table public.app_members enable row level security;
drop policy if exists "anon full access members dir" on public.app_members;
create policy "anon full access members dir" on public.app_members
  for all to anon using (true) with check (true);

-- Seed the owner as an admin so the Users tab exists before anyone else
-- signs in. name/email fill themselves in on the next sign-in.
insert into public.app_members (identity, email, role)
values ('trossi@battag.com', 'trossi@battag.com', 'Admin')
on conflict (identity) do update set role = 'Admin', blocked = false;
