-- ============================================================================
--  BidTagglia: contacts + activities.
--  Run in Supabase -> SQL Editor. Safe to re-run.
--
--  contacts   — people at the companies we bid to.
--  activities — something scheduled or logged against a bid: a site walk, an
--               RFI due date, a voicemail. `opportunity_id` is the bid it
--               belongs to (text, matching the rest of the app's habit of
--               keying opportunities by their id as text) and `contact_id` is
--               the person it involved, both optional.
--
--  Deleting a contact leaves its activities in place with no contact, which is
--  better than losing the record of what happened.
-- ============================================================================

create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text,
  phone      text,
  company    text,
  notes      text,
  created_at timestamptz not null default now()
);

create index if not exists contacts_company_idx on public.contacts(company);

create table if not exists public.activities (
  id             bigint generated by default as identity primary key,
  title          text not null,
  type           text,                 -- free text: the list is a suggestion
  scheduled_date date,
  opportunity_id text,
  contact_id     bigint references public.contacts(id) on delete set null,
  notes          text,
  created_at     timestamptz not null default now()
);

create index if not exists activities_scheduled_idx
  on public.activities(scheduled_date);
create index if not exists activities_opportunity_idx
  on public.activities(opportunity_id);

alter table public.contacts enable row level security;
drop policy if exists "anon full access contacts" on public.contacts;
create policy "anon full access contacts" on public.contacts
  for all to anon using (true) with check (true);

alter table public.activities enable row level security;
drop policy if exists "anon full access activities" on public.activities;
create policy "anon full access activities" on public.activities
  for all to anon using (true) with check (true);
